version: '3.9'
services:
  bunelysia:
    image: imbios/bun-node:latest-20-alpine
    env_file: ./.env
    container_name: bunelysia-${ENV}
    hostname: bunelysia-${ENV}
    network_mode: 'bridge'
    restart: unless-stopped
    tty: true
    stdin_open: true
    volumes:
      - .:/home/bun/app
    ports:
      - 3000:3000
    command: sh
# docker compose run --rm -i -t bunelysia sh
