version: '3.9'
services:
  bunelysia:
    image: nozich/bunode
    env_file: ./.env
    container_name: bunelysia-${ENV}
    hostname: bunelysia-${ENV}
    network_mode: 'bridge'
    restart: unless-stopped
    tty: true
    stdin_open: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/home/bun/app
    ports:
      - 3000:3000
      - 6499:6499
    command: sh
    working_dir: /home/bun/app
# docker compose run --rm -i -t bunelysia sh
